version: "3"

services:
  db:
    image: mysql:5.6    
    
    environment:
      MYSQL_ROOT_PASSWORD: password123 
    ports:
      - "3306:3306"

  atutor:
    image: "lnwza555/atutor"
      
    depends_on:
      - db
    ports:
      - "80:80"